### PR TITLE
Upgrade to Ruby 2.7 per 2.5 EOL

### PR DESCRIPTION
**Pull request by pnc**
See https://eleos.pagerduty.com/incidents/P4E66WR

### CODE REVIEW

**Review by jrubill — APPROVED** [review]
I'm going to approve this with the caveat that I don't know what we have running in lambda, but I'm assuming this bump in versions doesn't break anything.

**Comment by jrubill** [comment]
Oh while you're here, do you want to update the README as well? You've got ruby 2.5 hyperlinked

**Comment by pnc** [comment]
@jrubill Good call, updated. Since I'm on call let's deploy this together so you can see what that process looks like. (We have a few other node functions that do things for poipond, updating is similar but not identical.)

**Review by maravillas — APPROVED** [review]

**Comment by pnc** [comment]
@jrubill Do you mind trying the deployment instructions in the README and reporting back any trouble you have? Thank you!

**Pull request merged**
